# ESLint configuration for backend

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

env:
  node: true
  es2020: true

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  no-console: warn
  @typescript-eslint/no-explicit-any: error
  @typescript-eslint/explicit-function-return-types:
    - warn
    - allowExpressions: true
